require 'nokogiri'

courses = ["cs653/src/", "phys516/src/", "cs596/src/"]

def make_index(directory, children)
  fh = File.open(File.join(directory,"index.html"), "w")
  doc =  Nokogiri::HTML::Document.parse <<-EOHTML
  <h1>Index of #{ directory } </h1>
  <table>
  <tr><th>Name</th><th>Last modified</th><th>Size</th><th>Description</th></tr><tr><th colspan="5"><hr></th></tr>
  </table>
  <p>Automated index generated by using <a href="https://nokogiri.org/">Nokigiri</a></p>
  EOHTML
  # p doc.to_html
  puts "children of #{directory} are #{children}"
  body = doc.at_css "body"
  body.add_previous_sibling "<head>
  <title>Index of #{ directory } </title></head>"
  
  children.each do |child|
    tr            = doc.at_css "table"
    f = File.stat(File.join(directory, child))
    tr.add_child "<tr>
    <td><a href = #{ File.join(child) }> #{ child } </a></td>
    <td> #{ f.mtime }</td>
    <td align=\"right\">  #{ f.size } </td>
    <td> #{ f.ftype }</td></tr>"
  end
  puts doc.to_html
  doc.write_to(fh)
  puts "Generated index in " + File.join(directory,"index.html")  
end

def find_contents(directories)
  directory_children_map = {}
  directories.each do |directory| 
    children          = Dir.entries(directory).select do |entry|
      !(entry == '.' || entry == '..' ) and !(entry == 'index.html')
    end
    directory_children_map[directory] = children   
  end
  
  # Make index.html page 
  directory_children_map.each_pair do |directory, children|
    make_index(directory, children)        
  end  
  
  # Explore more files and folders in each directory and repeat the above process 
  directory_children_map.each_pair do |directory, children|
    deeper_directories = children.map {|entry| File.join(directory, entry)}.select {|entry| File.directory? entry}
    find_contents(deeper_directories)
  end
end

find_contents(courses)


